AllCops:
  Exclude:
    - db/**/*
    - bin/*
    - vendor/bundle/**/*
    - provision/**/*

  TargetRubyVersion: 2.4

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 160

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
