# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d0500ed3a04dda614eee19f060987c55b372a02c849369d0a540a0c01e99e3dccf157445b52fbffeccdf7aadf27ca870be8d54e889c6ac3fa0d0198813cc926

test:
  secret_key_base: 11748467907c99059446778632aedae69e5d46ab7a15096d26dae1be6908d814e74386679bed2aa2ae466289a69951819ca7d3b167b0f8dfcfba8a1dffd5c472

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
